
steps:
  - task: Cache@2
    inputs:
      key: 'docker | "$(Build.SourcesDirectory)/Dockerfile"'
      restoreKeys: |
        docker |
      path: $(Pipeline.Workspace)/.docker
    displayName: 'Cache Docker layers'

  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      command: 'buildAndPush'
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: $(imageName)
      dockerfile: $(dockerFilePath)
      tags: $(tag)
      buildContext: $(Build.SourcesDirectory)
